project:
  type: website
  output-dir: docs

website:
  title: "Emily Norton"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd   
      - analysis.qmd
      - Map_ballot_drop_boxes.Rmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full
    code-fold: true
    code-summary: "Show the code"

editor: visual

execute:
  freeze: auto  # re-render only when source changes

